import { Producto } from "../interfaces/Product";

export const productList: Producto[] = [
  /*{
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - 1000 Lumen - 10W",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "3,59",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-C410",
    "SKU": "MM105NXT82",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Light Bulb - GU10 CCT 110V 3PK",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "4,39",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-W3103PK",
    "SKU": "MM105NXT47",
    "Atributos": "Conexión Wi-Fi-Bombillo de luz blanca-Compatible con Amazon Alexa y Google Assistant-400 lumen-4W(equivalente a 40w)-110V /220V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt Solutions Connectivity - smart dual outdoor",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "4,59",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "NHP-O610",
    "SKU": "MM105NXT85",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt Solutions Home - Smart  plug 110/220v",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "7,05",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-S611",
    "SKU": "MM106NXT91",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt Solutions Connectivity - Smart plug RGB light",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "8,52",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-S610",
    "SKU": "MM106NXT68",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Smart 3 way switch",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "8,83",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHE-S300",
    "SKU": "MM106NXT33",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Light Bulb - A19 RGB 110V 2PK",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "9,39",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-C1102PK",
    "SKU": "MM106NXT71",
    "Atributos": "conexión WI-FI-Bombillo multicolor-Compatible con Amazon Alexa y Google Assistant-800 Lumen-9W(Equivalente a 60W)-110 V/ 220 V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt -Solutions Connectivity - NHB-W2104PK -  Light Bulb",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "11,87",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-W2104PK",
    "SKU": "MM105NXT44",
    "Atributos": "Paquete de 4-Conexión Wi-Fi-Compatible con Amazon Alexa y Google Assistant-110 V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - smart light switch",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "12,00",
    "Disponibilidad": "Inventario su localidad: 7",
    "Parte": "NHE-S100",
    "SKU": "MM105NXT66",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - CCT 6\" 110/220V",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "13,04",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-W710",
    "SKU": "MM106NXT62",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt Solutions Home - Smart plug 2 pack",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "13,26",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-S6112PK",
    "SKU": "MM106NXT92",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt  - Solutions Connectivity - NHP-D610",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "13,39",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-D610",
    "SKU": "MM105NXT37",
    "Atributos": "wireless-2 Toma corrientes-2 puertos USB-Compatible con Amazon Alexa y Google Assistant-1875 W de potencia máxima-200 joules"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Light Bulb - A19 CCT 110V 4PK",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "14,66",
    "Disponibilidad": "Inventario su localidad: 11",
    "Parte": "NHB-W1104PK",
    "SKU": "MM106NXT74",
    "Atributos": "Conexion Wi-Fi-Bombillo de luz blanca regulable-Compatible con Amazon Alexa y Google Assistant-800 Lumen-9W (Equivalente a 60 W)-110 V /220 V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Wall outlet USB",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "15,80",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHE-W100",
    "SKU": "MM105NXT88",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - Light Bulb - A19 RGB 110V 4PK",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "16,64",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-C1104PK",
    "SKU": "MM106NXT72",
    "Atributos": "conexión WI-FI-Bombillo multicolor-Compatible con Amazon Alexa y Google Assistant-800 Lumen-9W(Equivalente a 60W)-110 V/ 220 V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt Solutions Home - Now with TypeC ports",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "17,75",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-T615",
    "SKU": "MM107NXT32",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - Smart indoor 2K Cam",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "17,82",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-I710",
    "SKU": "MM106NXT46",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - 3 circuit switch",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "19,10",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHE-T100",
    "SKU": "MM106NXT37",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Administración de Energía",
    "Nombre": "Nexxt - Solutions Connectivity - wireless 4 outlet",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "22,49",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHP-E610",
    "SKU": "MM105NXT39",
    "Atributos": "Conexión Wi-Fi-4 toma corriente-4 puertos USB de carga-Compatible  con Amazon Alexa y Google Asistant-1875W de potencia máxim"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt NHC-P710 - Cámara de vigilancia de red - panorámico / inclinación",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "24,19",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-P710",
    "SKU": "MM106NXT64",
    "Atributos": "en interior-color (Día y noche)-1920 x 1080-focal fijado-audio-inalámbrico-Wi-Fi-H.264-CC 5 V"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Electrodomésticos",
    "Nombre": "Nexxt Solutions Connectivity Aroma Diffuser - smart wi-fi LED",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "28,01",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHA-A600",
    "SKU": "MM105NXT71",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - Indoor PTZ 2K RJ45",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "28,04",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-IP10",
    "SKU": "MM107NXT25",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - RGBIC LED Strip 5m",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "29,70",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-S613",
    "SKU": "MM106NXT83",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - Incluye sirena",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "29,74",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-D100",
    "SKU": "MM106NXT32",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - Indoor 2K baby cam",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "29,78",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-B100",
    "SKU": "MM106NXT67",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - RGB + CCT 12\" 110V",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "32,20",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-C810",
    "SKU": "MM106NXT61",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - Fixed 2K+ 5MP RJ45",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "33,28",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-OF10",
    "SKU": "MM107NXT21",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - Indoor 2K camera 2pk",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "34,45",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-I7102PK",
    "SKU": "MM106NXT47",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - Mickey Regular box",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "36,40",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "NHC-B100 MK",
    "SKU": "MM107NXT33",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - Minnie Regular Box",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "36,40",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "NHC-B100 MN",
    "SKU": "MM107NXT42",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - 2K Camera with light",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "37,05",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-F410",
    "SKU": "MM106NXT55",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Connectivity - LED RGBIC 4.9ft lamp",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "41,04",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-S710",
    "SKU": "MM106NXT39",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - PTZ 2K+ 5MP RJ45",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "41,29",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-OP10",
    "SKU": "MM107NXT23",
    "Atributos": ""
  },
  {
    "Categoria": "Redes",
    "Subcategoria": "Puentes y Enrutadores",
    "Nombre": "Nexxt Solutions Home - Router - Wireless Mesh",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "46,53",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NCM-X1800",
    "SKU": "NW231NXT32",
    "Atributos": "802.11a/b/g/n/ac/ax-Desktop-Mesh router AX1800"
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity Outdoor 2K - Smart Flood Light",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "48,19",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHC-F610",
    "SKU": "MM106NXT95",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Electrodomésticos",
    "Nombre": "Nexxt Solutions Connectivity - Incluye batería de respaldo",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "50,99",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHA-B100",
    "SKU": "MM106NXT63",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Iluminación",
    "Nombre": "Nexxt Solutions Home - LED strip and camera",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "54,52",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHB-S615",
    "SKU": "MM107NXT08",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity - Exterior de batería",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "55,24",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "nhc-o640",
    "SKU": "MM106NXT36",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Connectivity Outdoor 2K - Smart Flood Light",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "60,39",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "NHC-F610",
    "SKU": "MM105NXT40",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Electrodomésticos",
    "Nombre": "Nexxt Solutions Connectivity Pet Feeder - Camera 1080p",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "70,18",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NHA-P610",
    "SKU": "MM107NXT24",
    "Atributos": ""
  },
  {
    "Categoria": "Seguridad y Automatización",
    "Subcategoria": "Cámaras",
    "Nombre": "Nexxt Solutions Home - Includes solar panel",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "72,46",
    "Disponibilidad": "Inventario su localidad: 13",
    "Parte": "NHC-OP20S",
    "SKU": "MM107NXT26",
    "Atributos": ""
  },
  {
    "Categoria": "Redes",
    "Subcategoria": "Puentes y Enrutadores",
    "Nombre": "Nexxt Solutions Home - Router - Wireless Mesh",
    "Marca": "Nexxt Solutions Connectivity",
    "Precio": "89,76",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "NCM-X18002PK",
    "SKU": "NW231NXT33",
    "Atributos": "802.11a/b/g/n/ac/ax-Desktop-Mesh routerAX18002pk"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Mouse para Gaming Xtech XTM-510 Bellixus USB - Resolución ajustable de hasta 2400 ppp - Luces LED de 3 colores",
    "Marca": "Xtech",
    "Precio": "7,94",
    "Disponibilidad": "Inventario su localidad: 17",
    "Parte": "XTM-510",
    "SKU": "ID011XTK07",
    "Atributos": "Cable sin enredos-Sensor: Óptico-Botones: 6-Iluminado: Sí-Longitud del cable: 5,2 pies, trenzado"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Mouse para Gaming Xtech XTM-610 Lethal Haze - Resolución ajustable de hasta 3200 ppp - Luces LED de 4 colores",
    "Marca": "Xtech",
    "Precio": "7,47",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "XTM-610",
    "SKU": "ID011XTK11",
    "Atributos": "Cable sin enredos-para juegos 3D de 6 botones-Sensor: Óptico-Botones: 6-Iluminado: Sí-Longitud del cable: 5,2 pies, trenzado"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Arena Blk-PMP-01M",
    "Marca": "Primus Gaming",
    "Precio": "5,62",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMP-01M",
    "SKU": "AC260PGL01",
    "Atributos": ""
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Arena Blk-PMP-01XXL",
    "Marca": "Primus Gaming",
    "Precio": "15,00",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMP-01XXL",
    "SKU": "AC260PGL04",
    "Atributos": ""
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Arena Desig-PMP-11L",
    "Marca": "Primus Gaming",
    "Precio": "12,61",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMP-11L",
    "SKU": "AC260PGL06",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Teclado para Gaming Xtech XTK-510S - Español - Iluminación LED Multi-color con efectos de luz",
    "Marca": "Xtech",
    "Precio": "10,25",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTK-510S",
    "SKU": "ID222XTK30",
    "Atributos": "Conexión USB inmediata-Descansa-palmas integrado con acabado texturizado"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Accesorios para Portátiles",
    "Nombre": "Xtech - Notebook stand - XTA-160",
    "Marca": "Xtech",
    "Precio": "13,48",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTA-160",
    "SKU": "AN001XTK04",
    "Atributos": "Kyla-gaming-Laptop-size compatibility: Up to 17in-Number of fans: 6 LED Blue light-Adjustable height: 3 positions-Connectivity: 2 USB ports"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Xtech - Headset - Wired",
    "Marca": "Xtech",
    "Precio": "9,10",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTH-500",
    "SKU": "MM221XTK73",
    "Atributos": "XTH-500-Voracis-Gaming-Connection type: Two 3.5mm plugs for mic and audio-Compatible platforms: PC-Buttons: Volume control in control capsule-Cable length: 6.5ft"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Logitech Wireless Gaming Mouse G502 Lightspeed - Ratón - óptico",
    "Marca": "Logitech",
    "Precio": "83,91",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "910-005565",
    "SKU": "ID022LOG47",
    "Atributos": "11 botones-inalámbrico-2.4 GHz-receptor inalámbrico USB"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Primus Gaming - Mouse - USB",
    "Marca": "Primus Gaming",
    "Precio": "17,50",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMO-102",
    "SKU": "ID011PGL04",
    "Atributos": "Wired-Gladius8200T PMO-102"
  },
  {
    "Categoria": "Maletines",
    "Subcategoria": "Mochilas",
    "Nombre": "Xtech Insurgent XTB-507 Mochila para laptop 16.5” y accesorios de videojuegos - Nylon durable - Gaming",
    "Marca": "Xtech",
    "Precio": "25,00",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTB-507",
    "SKU": "AN100XTK30",
    "Atributos": "Color Negro y Rojo-Bolsillo Antirrobo-Panel posterior acolchado con tecnología de ventilación Airflow"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Xtech - Headset - Wired",
    "Marca": "Xtech",
    "Precio": "14,11",
    "Disponibilidad": "Inventario su localidad: 2",
    "Parte": "XTH-531",
    "SKU": "MM221XTK88",
    "Atributos": "XTH-531-Kalamos-Gaming-Color: Black w Red accents-Connection type: USB plug- Directivity: Omnidirectional-Buttons: Command Capsule (with volume +, Volume -, audio mute, and Microphone mute-Cable length: 6.5ft"
  },
  {
    "Categoria": "Muebles",
    "Subcategoria": "Sillas",
    "Nombre": "Primus Gaming - Chair 100T PCH-102BK",
    "Marca": "Primus Gaming",
    "Precio": "190,00",
    "Disponibilidad": "Inventario su localidad: 4",
    "Parte": "PCH-102BK",
    "SKU": "AM160PGL09",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Logitech G915 TKL Tenkeyless LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard - Teclado - retroiluminación",
    "Marca": "Logitech",
    "Precio": "156,20",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "920-009495",
    "SKU": "ID223LOG73",
    "Atributos": "USB, Bluetooth, 2.4 GHz-inglés-interruptor: GL Tactile-carbón"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Logitech Gaming Mouse G203 LIGHTSYNC - Ratón - óptico",
    "Marca": "Logitech",
    "Precio": "18,55",
    "Disponibilidad": "Inventario su localidad: 17",
    "Parte": "910-005792",
    "SKU": "ID023LOG05",
    "Atributos": "6 botones-cableado-USB-azul"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Logitech Gaming Mouse G203 LIGHTSYNC - Ratón - óptico",
    "Marca": "Logitech",
    "Precio": "19,97",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "910-005851",
    "SKU": "ID023LOG06",
    "Atributos": "6 botones-cableado-USB-lila"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Logitech G733 LIGHTSPEED Wireless RGB Gaming Headset - Auricular - 7.1 canales",
    "Marca": "Logitech",
    "Precio": "128,00",
    "Disponibilidad": "Inventario su localidad: 7",
    "Parte": "981-000863",
    "SKU": "MM120LOG98",
    "Atributos": "tamaño completo-2,4 GHz-inalámbrico-negro"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - PHS-90 - Earphones",
    "Marca": "Primus Gaming",
    "Precio": "18,00",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PHS-90",
    "SKU": "MM221PGL04",
    "Atributos": "Para Computer / Para Game console-Wired-3.5mm w/Mic ARCUS90T"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - PHS-101 - Headset",
    "Marca": "Primus Gaming",
    "Precio": "30,50",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "phs-101",
    "SKU": "MM221PGL05",
    "Atributos": "Para Computer / Para Game console-Wired-Arcus100T"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Xtech - XTH-520BK - Headset",
    "Marca": "Xtech",
    "Precio": "10,37",
    "Disponibilidad": "Inventario su localidad: 8",
    "Parte": "XTH-520BK",
    "SKU": "MM221XTK30",
    "Atributos": "Para Computer / Para Game console-Wired-Mono chat gaming"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "A-Data - Headphones - Wired",
    "Marca": "A-Data",
    "Precio": "114,05",
    "Disponibilidad": "Inventario su localidad: 2",
    "Parte": "XPGPRECOG",
    "SKU": "MM000ADT04",
    "Atributos": "Precog Gaming"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Logitech PRO X SUPERLIGHT Wireless Gaming Mouse - Ratón - óptico",
    "Marca": "Logitech",
    "Precio": "73,29",
    "Disponibilidad": "Inventario su localidad: 16",
    "Parte": "910-005940",
    "SKU": "ID023LOG28",
    "Atributos": "5 botones-inalámbrico, cableado-2.4 GHz-blanco"
  },
  {
    "Categoria": "Componentes Informáticos",
    "Subcategoria": "Cajas / Gabinetes",
    "Nombre": "Xtech Gaming Series PHOBOS - MDT - ATX",
    "Marca": "Xtech",
    "Precio": "40,70",
    "Disponibilidad": "Inventario su localidad: 10",
    "Parte": "XT-GMR4",
    "SKU": "CS515XTK04",
    "Atributos": "panel lateral con ventana (cristal templado)-sin fuente de alimentación (ATX)-negro-USB/Audio"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Xtech - XTM-810 - Mouse",
    "Marca": "Xtech",
    "Precio": "8,98",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTM-810",
    "SKU": "ID011XTK23",
    "Atributos": "USB-Wired-Black-Gaming Stauros 7200d"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus ARCUS200S-BT - Auriculares internos con micro - en oreja",
    "Marca": "Primus Gaming",
    "Precio": "34,60",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PWH-200",
    "SKU": "MM221PGL06",
    "Atributos": "Bluetooth-inalámbrico"
  },
  {
    "Categoria": "Monitores",
    "Subcategoria": "Monitores",
    "Nombre": "ViewSonic OMNI Gaming VX2418-P-mhd - Gaming - monitor LED",
    "Marca": "Viewsonic",
    "Precio": "228,76",
    "Disponibilidad": "Inventario su localidad: 17",
    "Parte": "VX2418-P-MHD",
    "SKU": "MT862VWS88",
    "Atributos": "gaming-24\" (23.8\" visible)-1920 x 1080 Full HD (1080p) @ 165 Hz-MVA-250 cd/m²-4000:1-1 ms-2xHDMI, DisplayPort-altavoces"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Logitech G435 LIGHTSPEED Wireless Gaming Headset - Auricular - tamaño completo",
    "Marca": "Logitech",
    "Precio": "58,87",
    "Disponibilidad": "Inventario su localidad: 10",
    "Parte": "981-001049",
    "SKU": "MM000LOG66",
    "Atributos": "Bluetooth / LIGHTSPEED-inalámbrico-negro-certificado Discord-para P/N: GMA670V2"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Logitech G435 LIGHTSPEED Wireless Gaming Headset - Auricular - tamaño completo",
    "Marca": "Logitech",
    "Precio": "80,25",
    "Disponibilidad": "Inventario su localidad: 19",
    "Parte": "981-001073",
    "SKU": "MM000LOG67",
    "Atributos": "Bluetooth / LIGHTSPEED-inalámbrico-blanco"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Logitech Gaming G840 XL League of Legends Edition - Alfombrilla de ratón",
    "Marca": "Logitech",
    "Precio": "39,95",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "943-000543",
    "SKU": "AC000LOG23",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Xtech - XTM-411 - Mouse",
    "Marca": "Xtech",
    "Precio": "6,55",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTM-411",
    "SKU": "ID011XTK24",
    "Atributos": "USB-Wired-Black-Gaming 3600dpi"
  },
  {
    "Categoria": "Monitores",
    "Subcategoria": "Monitores",
    "Nombre": "Samsung Odyssey G5 S27AG550EN - Monitor LED - gaming",
    "Marca": "Samsung",
    "Precio": "521,41",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "LS27AG550ENXZA",
    "SKU": "MT862SAM52",
    "Atributos": "curvado-27\"-2560 x 1440 WQHD @ 165 Hz-VA-300 cd/m²-2500:1-HDR10-1 ms-HDMI, DisplayPort-negro"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Micrófonos",
    "Nombre": "Xtech - Microphone - Computer",
    "Marca": "Xtech",
    "Precio": "8,18",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTS-680",
    "SKU": "MM221XTK34",
    "Atributos": "Omni-directional-Wired-USB Gaming XTS-680"
  },*/
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - PHS-210 - Headset",
    "Marca": "Primus Gaming",
    "Precio": "65,71",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PHS-210",
    "SKU": "MM221PGL14",
    "Atributos": "Para Computer / Para Game console-Wired-3.5mm Arcus210S",
    "Imagen": "https://primusgaming-frontend.s3.amazonaws.com/media/img/PHS-210_36.jpg"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Combos de Teclado y Ratón",
    "Nombre": "Xtech - Keyboard, mouse and mouse pad - Wired",
    "Marca": "Xtech",
    "Precio": "17,27",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTK-535S",
    "SKU": "ID223XTK06",
    "Atributos": "Spanish-USB-Black-Gaming XTK-535S",
    "Imagen": "https://xtech-frontend.s3.amazonaws.com/media/img/XTK-535S_Land.jpg"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "ASTRO Gaming A10 Gen 2 - Auricular - tamaño completo",
    "Marca": "Logitech",
    "Precio": "69,59",
    "Disponibilidad": "Inventario su localidad: 4",
    "Parte": "939-002062",
    "SKU": "MM121LOG19",
    "Atributos": "cableado-blanco"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "ASTRO Gaming A10 Gen 2 - Auricular - tamaño completo",
    "Marca": "Logitech",
    "Precio": "69,58",
    "Disponibilidad": "Inventario su localidad: 5",
    "Parte": "939-002076",
    "SKU": "MM121LOG21",
    "Atributos": "cableado-lila"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "ASTRO Gaming A10 Gen 2 - Auricular - tamaño completo",
    "Marca": "Logitech",
    "Precio": "70,30",
    "Disponibilidad": "Inventario su localidad: 2",
    "Parte": "939-002083",
    "SKU": "MM121LOG22",
    "Atributos": "cableado-menta"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Arena Design-PMP-12M",
    "Marca": "Primus Gaming",
    "Precio": "7,37",
    "Disponibilidad": "Inventario su localidad: 2",
    "Parte": "PMP-12M",
    "SKU": "AC260PGL08",
    "Atributos": ""
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - ArenaDesig-PMP-13XXL",
    "Marca": "Primus Gaming",
    "Precio": "17,46",
    "Disponibilidad": "Inventario su localidad: 8",
    "Parte": "PMP-13XXL",
    "SKU": "AC260PGL09",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Primus Gaming - PMO-S202ML - Mouse",
    "Marca": "Primus Gaming",
    "Precio": "13,02",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "PMO-S202ML",
    "SKU": "ID011PGL08",
    "Atributos": "USB-Wired-Mandalorian G 12400T"
  },
  {
    "Categoria": "Celulares",
    "Subcategoria": "Accesorios",
    "Nombre": "Razer Kishi V2 - Mando de videojuegos - cableado",
    "Marca": "Razer",
    "Precio": "53,55",
    "Disponibilidad": "Inventario su localidad: 4",
    "Parte": "RZ06-04180100-R3U1",
    "SKU": "AC000RZR85",
    "Atributos": "para Android"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Micrófonos",
    "Nombre": "Primus Gaming - Microphone - Computer",
    "Marca": "Primus Gaming",
    "Precio": "29,00",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMI-101",
    "SKU": "MM000PGL02",
    "Atributos": "Cardioid-Wired-ÉTHOS100T PMI-101"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Xtech - XTM-720 - Mouse",
    "Marca": "Xtech",
    "Precio": "7,82",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTM-720",
    "SKU": "ID011XTK42",
    "Atributos": "USB-Wired-Black-Gaming 7200dpi"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Xtech - Mouse pad with wrist pillow - Gaming Pink XTA-530",
    "Marca": "Xtech",
    "Precio": "4,45",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTA-530",
    "SKU": "AC001XTK10",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Astro Gaming - Headphones - Wired",
    "Marca": "Logitech",
    "Precio": "28,93",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "981-001285",
    "SKU": "100017221",
    "Atributos": "Sonido estéreo digit"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Auriculares y Manos Libres",
    "Nombre": "Astro Gaming - Headphones - Wired",
    "Marca": "Logitech",
    "Precio": "30,98",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "981-001280",
    "SKU": "100017222",
    "Atributos": "Ruido giratorio"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Xtech - Keyboard and mouse set - Wired",
    "Marca": "Xtech",
    "Precio": "15,73",
    "Disponibilidad": "Inventario su localidad: 11",
    "Parte": "XTK-531S",
    "SKU": "ID223XTK13",
    "Atributos": "Spanish-USB-Black-Backlight: Multi-color LEDs-Gaming XTK-531S"
  },
  {
    "Categoria": "Monitores",
    "Subcategoria": "Monitores",
    "Nombre": "ViewSonic OMNI Gaming VX2416 - Monitor LED - gaming",
    "Marca": "Viewsonic",
    "Precio": "189,67",
    "Disponibilidad": "Inventario su localidad: 11",
    "Parte": "VX2416",
    "SKU": "MT863VWS14",
    "Atributos": "24\" (23.8\" visible)-1920 x 1080 Full HD (1080p) @ 100 Hz-IPS-250 cd/m²-1000:1-1 ms-HDMI, DisplayPort-altavoces"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Xtech - Keyboard and mouse set - Wired",
    "Marca": "Xtech",
    "Precio": "14,72",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTK-540S",
    "SKU": "ID223XTK11",
    "Atributos": "Spanish-USB-Pink-Gaming-XTK-540S"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Razer Basilisk - Mouse - Bluetooth",
    "Marca": "Razer",
    "Precio": "63,27",
    "Disponibilidad": "Inventario su localidad: 3",
    "Parte": "RZ01-04870100-R3U1",
    "SKU": "ID001RZR90",
    "Atributos": "Wireless-Ergonomic Gaming Mouse."
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Primus Gaming - Keyboard - Wired",
    "Marca": "Primus Gaming",
    "Precio": "25,00",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "PKS-S092DV-S",
    "SKU": "ID000PGL18",
    "Atributos": "Spanish-USB-Ergonomic Design-Darth V PKS-S092DV-S"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Ahsoka Tano PMP-S15AT-XXL",
    "Marca": "Primus Gaming",
    "Precio": "17,00",
    "Disponibilidad": "Inventario su localidad: 13",
    "Parte": "PMP-S15AT-XXL",
    "SKU": "AC260PGL15",
    "Atributos": ""
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - PHS-S110AT - Headset",
    "Marca": "Primus Gaming",
    "Precio": "25,00",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "PHS-S110AT",
    "SKU": "MM221PGL25",
    "Atributos": "Para Computer / Para Game console-Wired-Ahsoka Tano Arcus110T"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Xtech - Headphones with microphone - Para Computer / Para Portable electronics / Para Tablet / Para Cellular phone",
    "Marca": "Xtech",
    "Precio": "15,48",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTH-M565SG",
    "SKU": "MM221XTK49",
    "Atributos": "Wired-Gaming"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Xtech - XTM-M520SM - Mouse",
    "Marca": "Xtech",
    "Precio": "8,88",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTM-M520SG",
    "SKU": "ID011XTK29",
    "Atributos": "USB-Wired-Gaming"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Xtech - Mouse pad - Gaming",
    "Marca": "Xtech",
    "Precio": "10,13",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTA-M15SG-XXL",
    "SKU": "AC001XTK16",
    "Atributos": ""
  },
  {
    "Categoria": "Computadores",
    "Subcategoria": "Portátiles",
    "Nombre": "Lenovo IdeaPad Gaming 3 15IAH7 - Notebook - 15.6",
    "Marca": "Lenovo",
    "Precio": "1035,63",
    "Disponibilidad": "Inventario su localidad: 1",
    "Parte": "82S9010HLM",
    "SKU": "NT061LEN55",
    "Atributos": "Intel Core i7 i7-12650H-512 GB SSD-Windows 11 Home-1-year warranty"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Teclados y Teclados de Números",
    "Nombre": "Primus Gaming - Keyboard - Wired",
    "Marca": "Primus Gaming",
    "Precio": "32,35",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PKS-093S",
    "SKU": "ID000PGL19",
    "Atributos": "Spanish-USB-Ball 91T PKS-093S"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Parlantes / Bocinas / Cornetas",
    "Nombre": "Xtech - Speakers - 2.0-channel",
    "Marca": "Xtech",
    "Precio": "12,85",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "XTS-131",
    "SKU": "MM222XTK96",
    "Atributos": "Black-Gaming with Led Light XTS-131"
  },
  {
    "Categoria": "Monitores",
    "Subcategoria": "Monitores",
    "Nombre": "LG UltraGear 27GR95QE-B - OLED monitor - 27",
    "Marca": "LG",
    "Precio": "1140,37",
    "Disponibilidad": "Inventario su localidad: 5",
    "Parte": "27GR95QE-B",
    "SKU": "MT001LGE25",
    "Atributos": "2560 x 1440-DisplayPort / HDMI-Gaming Monitor"
  },
  {
    "Categoria": "Muebles",
    "Subcategoria": "Sillas",
    "Nombre": "Primus Gaming - Limited edition",
    "Marca": "Primus Gaming",
    "Precio": "264,76",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PCH-S203GR",
    "SKU": "AM160PGL20",
    "Atributos": ""
  },
  {
    "Categoria": "Muebles",
    "Subcategoria": "Sillas",
    "Nombre": "Primus Gaming - Limited edition DS",
    "Marca": "Primus Gaming",
    "Precio": "264,76",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PCH-S203DS",
    "SKU": "AM160PGL21",
    "Atributos": ""
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Primus Gaming - Mouse - USB",
    "Marca": "Primus Gaming",
    "Precio": "29,88",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMO-S203GR",
    "SKU": "ID011PGL11",
    "Atributos": "Wired-PMO-S203GR"
  },
  {
    "Categoria": "Periféricos",
    "Subcategoria": "Ratones",
    "Nombre": "Primus Gaming - Mouse - USB",
    "Marca": "Primus Gaming",
    "Precio": "29,88",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMO-S203DS",
    "SKU": "ID011PGL12",
    "Atributos": "Wired-PMO-S203DS"
  },
  {
    "Categoria": "Accesorios para Computadores",
    "Subcategoria": "Mouse Pads y Wrist Pads",
    "Nombre": "Primus Gaming - Mouse pad - Dark Side MousePad XXL",
    "Marca": "Primus Gaming",
    "Precio": "14,63",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PMP-S15DS-XXL",
    "SKU": "AC260PGL20",
    "Atributos": ""
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - Headset - Para Game console / Para Home audio / Para Portable electronics / Para Tablet / Para Cellular phone",
    "Marca": "Primus Gaming",
    "Precio": "43,99",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PHS-S110GR",
    "SKU": "MM221PGL40",
    "Atributos": "Wired-Grogu Headset"
  },
  {
    "Categoria": "Audio y Video",
    "Subcategoria": "Auriculares",
    "Nombre": "Primus Gaming - Headset - Para Game console / Para Home audio / Para Portable electronics / Para Tablet / Para Cellular phone",
    "Marca": "Primus Gaming",
    "Precio": "43,99",
    "Disponibilidad": "Inventario su localidad: más de 20",
    "Parte": "PHS-S110DS",
    "SKU": "MM221PGL41",
    "Atributos": "Wired-Dark Side Headset"
  },
  {
    "Categoria": "Maletines",
    "Subcategoria": "Mochilas",
    "Nombre": "Xtech - Notebook carrying backpack - 17",
    "Marca": "Xtech",
    "Precio": "27,35",
    "Disponibilidad": "Inventario su localidad: 18",
    "Parte": "XTB-508",
    "SKU": "AN100XTK40",
    "Atributos": "Black-Gaming Battlestash  XTB-508"
  }
]